### ISSUE TITLE
jon gough pr for logbook

### ISSUE THREAD

**Issue by rgleason** [ptulp/LogbookKonni-1.2#16]
Jon gough has a PR on Konni's repos. It is about 3 yrs old and it adds a row and fixes saving to prevent losing info.

**Comment by ptulp** [comment]
That fix went into the delatbabel/LogbookKonni-1.2 stream in 2014.
Konni's repos cannot be accessed so we cannot change that PR there.

**Comment by rgleason** [comment]
Sorry. Thanks
