### ISSUE TITLE
ov50 -branch - wxEVT_GRID_CELL_CHANGE  -130 errors.

### ISSUE THREAD

**Issue by rgleason** [ptulp/LogbookKonni-1.2#20]
https://ci.appveyor.com/project/rgleason/logbookkonni-pi/builds/22910204
Multiple instances of:
```

LogbookDialog.cpp(2291): error C2065: 'wxEVT_GRID_CELL_CHANGE':  -->wxEVT_GRID_CELL_CHANGED
LogbookDialog.cpp(2630): error C2039: 'SetLabelValue': is not a member of 'wxGrid' 
LogbookDialog.cpp(3817): error C2039: 'SetColumnWidth': is not a member of 'wxGrid' 
LogbookDialog.cpp(4420): warning C4996: 'wxFontBase::SetWeight': deprecated: use wxFONTWEIGHT_XXX constants instead of wxLIGHT/wxNORMAL/wxBOLD 
LogbookDialog.cpp(4314): error C2664: 'void wxGrid::SetCellValue(const wxGridCellCoords &,const wxString &)': cannot convert argument 1 from 'wxString' to 'int' 
LogbookDialog.cpp(4473): error C2039: 'SetColumnWidth': is not a member of 'wxGrid' --> SetColSize
LogbookDialog.cpp(8924): error C2065: 'wxEVT_GRID_CELL_CHANGE': undeclared identifier  -->wxEVT_GRID_CELL_CHANGED
LogbookOptions.cpp(513): warning C4996: 'wxFont::wxFont': deprecated: use 
Maintenance.cpp(603): error C2664: 'void wxGrid::SetCellBackgroundColour(int,int,const wxColour &)': cannot convert argument 1 from 'wxColour' to 'int'
Maintenance.cpp(641): error C2664: 'void wxGrid::SetCellBackgroundColour(int,int,const wxColour &)': cannot convert argument 1 from 'wxColour' to 'int' 
OverView.cpp(1008): error C2039: 'GetCols': is not a member of 'wxGrid'   --->GetCol
OverView.cpp(1017): error C2039: 'GetRows': is not a member of 'wxGrid'   ---> GetRow
OverView.cpp(1252): error C2039: 'GetCols': is not a member of 'wxGrid'  ---> GetCols


```

**Comment by ptulp** [comment]
Rick,

Rasbat has already found all the differences for 4.99/5.0
See here for all changes:
https://github.com/Rasbats/LogbookKonni-1.2/commit/af3675980d0f6021822f9768d7154fb299325e36

Regards,
Peter

**Comment by rgleason** [comment]
http://wxwindowsjp.osdn.jp/docs/html/wx/wx188.htm#wxgridtablebasesetrowlabelvalue

**Comment by rgleason** [comment]
Well That's Good!  I was just halfway through it, down to 70 errors. 
Why isn't it up on the website? https://opencpn.org/OpenCPN/atp/48fb3bOH/5plugs.html

He has a  Release version here.  https://github.com/Rasbats/LogbookKonni-1.2/releases

What should I do?

**Comment by rgleason** [comment]
Maybe I'll save my appveyor file locally. 
Delete my ov50 branch.
Create a new ov50 branch.
Create a PR from Mike's repos.
Then add my ov50 appveyor.
Then if you want, I can make a PR to your ov50 branch,
and if you can add the Release file  to your Logbook repos that would be good.
Same for Polar_pi and Findit_pi
Are there any others?
At your convenience of course. 
Thanks.

**Comment by rgleason** [comment]
Done
