### ISSUE TITLE
JonGough PR

### ISSUE THREAD

**Issue by rgleason** [ptulp/LogbookKonni-1.2#22]
I wonder if Jon Gough's PR should be merged?
https://github.com/delatbabel/LogbookKonni-1.2/pulls

I don't know about  nkissel's  
Initialize sails strings arrays
or 
Fast Access dialog.

If not, perhaps they should be closed?

**Comment by ptulp** [comment]
Rick,
I have added the PR's from Jon and nkissel.
I would like to look and test the Fast Access dialog before adding them.
Hopefully I have some time for that in the summer.

**Comment by rgleason** [comment]
Thanks Peter. Much appreciated.
Perhaps someone else will also give it a try. The author did write back to explain how it works as an Option. See the notes in the PR.
